const TYPES = {
  ACCORDION_SECTION_SELECT: "ACCORDION_SECTION_SELECT",
  FONTS_LOADED: "FONTS_LOADED",
  BOOKMARK_TOGGLE: "BOOKMARK_TOGGLE",
  FETCH_DATA: "FETCH_DATA",
  FETCH_USER_INFORMATION: "FETCH_USER_INFORMATION",
  FLIGHT_SELECT: "FLIGHT_SELECT",
  SET_FLIGHT_INIT: "SET_FLIGHT_INIT",
  HOTEL_SELECT: "HOTEL_SELECT",
  SET_HOTEL_INIT: "SET_HOTEL_INIT",
  CAR_SELECT: "CAR_SELECT",
  SET_CAR_INIT: "SET_CAR_INIT"
};

export default TYPES;
